#! /usr/bin/env bash

timestamp="$(date +"%F_%T")"
python3 main.py --train_csv_file GI_keras_train_qa.csv \
    --glove_embed_file /nfs/mercury-11/u113/projects/AIDA/glove.840B.300d.txt.pkl \
    --run_prediction \
    --source_dataset GI \
     --epoch 5 --fix_gpu 1  | tee -a GI_keras_vse_runlog_$timestamp_${1:-orig_joint_model}.txt 
